version: '3.3'
services:
  monorepo:
    container_name: monorepo
    working_dir: /app
    build:
      context: ./
      dockerfile: ./infra/dev/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./infra/dev/.env
    ports:
      - '4000:4000'
      - '3030:3030'
      - '3333:3333'
    restart: always
